### ISSUE TITLE
home page slider text overlay size and position on wide devices/browsers

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#23]
I've been experimenting with different device sizes via screenfly. This ticket is about those widths be enough to leave the primary header layout in place (i.e., fairly wide to huge).
- At widths greater than about 1366px, the overlay text starts to crawl partly below the fold, and this gets worse the wider from there we go. It seems to be because the text top or bottom is pinned to a certain percentage height of the slider(?) and as the width gets bigger, the image scales in height correspondingly. Could we instead try something aimed at keeping the full overlay text visible on screen when we are treating it as an actual overlay (i.e., not on small/mobile), even if the image is pushing the footer etc further down? 
- We're very tight to the viewport edge on the right-hand side on widths less than 800px. max-width for the overlay container is currently pegged in CSS to a specific pixel value (829px). What would happen if we tried using a percentage or something else here that pulled us back a little bit from the right edge when our width is less than 800px, but we're still not in narrow mode (wherein the overlay is positioned below the image, which is fine)?
- In keeping with our overall "less demonstrative" direction on fonts, can we take the text down a peg or two in the overlay? Maybe something like `h3 {font-size: 20px, font-weight: 500, letter-spacing: 0.4px etc.}` and `p {font-size: 18px, etc. }`?

**Comment by kevintbrooks** [comment]
1) There really isn't a good way to tell where the "fold" is on a screen. To illustrate, take a look at 1366 wide on my screen. We could lock the height of the slide at certain widths to keep the text at a certain vertical point, but it would crop the slide image. Thoughts?
![screen shot 2015-06-04 at 3 13 37 pm](https://cloud.githubusercontent.com/assets/1392386/7992277/4b9ff480-0acc-11e5-97f0-446cdb0e9f80.png)

2) I'm not clear on the issue here - we kick over to 'narrow' view at 959px, so you should not be seeing the overlay at lower resolutions (unless you've resized without refreshing).

3) Pushed some edits here.

**Comment by paregorios** [comment]
I'm going to close this ticket. But I'm still not happy with the behavior of overlay text on wide browsers, so will be opening a new ticket for that issue alone.
