### ISSUE TITLE
home page carousel style

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#7]
The comps led us to expect:
-  wall-to-wall imagery on the home page
- imagery resizing to match browser width

But right now we see a right and left dead space (with arrows) on wider screens and the imagery stays the same size (i.e. underflows beyond browser sides)  as you narrow the browser window.

**Comment by kevintbrooks** [comment]
@paregorios As illustrated here, http://isaw.icscreative.com/, the code provided did provide a fully responsive slider on the homepage.

@alecpm It appears the slider library is not responsive. I've attempted to make some updates to get this to work, but it's proving a time consuming. Is there any way we can use the code I provided (which relies on the jQuery Cycle2 library?)

**Comment by skleinfeldt** [comment]
@alecpm will be doing some more work on this.

**Comment by alecpm** [comment]
Before I start work on this, I want to note why it's using the markup it currently uses.  In order to allow reasonable TTW management of the carousel, we're using a 3rd-party addon called EasySlider which provides a UI for creating slides and overlay text as well as setting slider parameters.  That addon provides its own (fairly similar) markup and JS.  We were hoping we could use the JS for that addon and modify the styles to fit the theme.  Unfortunately, the slider JS doesn't really accommodate responsiveness (since it uses a fixed value for the slide transition width).  I made JS and CSS modifications that allow it to be statically responsive (i.e. it will fill any fixed browser width), but not dynamically responsive.

Making it dynamically responsive will require either forking the package to update the JS to allow for responsiveness, or overriding the viewlet that provides the slider to use the markup and JS from the design to render the TTW created carousel slides.  The latter will implement the theme more exactly, but may be more limiting in terms of what the slides can contain.  The former option should be a bit quicker to implement, but will still not match the theme exactly.

**Comment by paregorios** [comment]
TTW management of the slider settings is essential for us. The fix made by @alecpm to make the slider statically responsive is good progress.

More important to us than dynamic responsiveness is the other bullet I raised in the initial comment on this issue, which I'll reiterate here with more detail:

If the browser width is wider than 1024px, the slider doesn't fill it. We see gray space (background color on something) to right and left of the slider. Like this:

![trapped-grey](https://cloud.githubusercontent.com/assets/263285/7823542/2f58bacc-03ca-11e5-98af-841787a25543.jpg)

We'd like the slider to fill the browser window always. And no ugly gray arrows to either side please (if you scroll left or right you'll see them).

And also this business with the arrows is probably related to the following: the slider, or a container it's in, seems to be bigger than another container it's in and the overflow behavior seems set to "scroll". Depending on the size of the browser window, you can get "stuck" in that inner container, scrolling the slider around in its little prison, and you get more and more enraged at not being able to scroll down the page.

![scrolly-badness](https://cloud.githubusercontent.com/assets/263285/7823609/bc1db6ce-03ca-11e5-9c29-a963904797a6.png)

**Comment by alecpm** [comment]
Those arrows should no longer appear (some CSS that should have hidden them out of date due to caching).  I'm surprised you're seeing the image smaller than the window at 1024px, that does happen to me here, but only at 1421px (the width of the image).  It should currently be scaling it up to the actual image size, but I can adjust it to scale beyond that size (though only the initial window size).

**Comment by alecpm** [comment]
The image scaling has been adjusted to allow scaling up the images to the full browser width.

**Comment by paregorios** [comment]
closing as resolved, but note now #18
