### ISSUE TITLE
how can we suppress minicalendar portlet on all event items?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#72]
It's interfering with the event information

**Comment by alecpm** [comment]
This is a little tricky.  Since the event view relies on the event details portlet, we can't just disable portlets or that column in the template.  We could alter the view to manually render that portlet, which would mean that no other portlets could be added to that column for individual events.  Alternatively, we could add an event handler and migration step that explicitly blocked parent portlets on all events when they are created.  Finally, the simplest solution would be to use a collection for the events section home page and apply the mini-calendar only to that page and rather than to the entire section.  I'll try the last solution first, since it's the simplest.

**Comment by paregorios** [comment]
I like the last solution too. Is the right thing to do to implement that somehow in production before the switchover, or should we just put that on checklist of manual fixes?

**Comment by alecpm** [comment]
This is done on the dev server.  It can be implemented on production to ease migration, but the custom view will still need to be applied via the display menu (i.e. at least that should be put on the list of manual fixes).

**Comment by paregorios** [comment]
Question:

What are the steps we should follow to implement on production?  I assume: add an appropriate collection as child of /events and make it the display item for the container. I understand why the custom view will need to be applied after the fact.

**Comment by paregorios** [comment]
In any case, let's please keep this issue open until we've figured out where we are going to document manual steps for the theme upgrade. That's on my agenda for today's standup.

**Comment by skleinfeldt** [comment]
As discussed in standup, https://github.com/isawnyu/isaw.web/blob/master/PROD_SNAPSHOT.txt is the right place to document. @alecpm can you please make sure this is added to that document?

**Comment by alecpm** [comment]
I've documented steps for creating the collection, making it the default view and changing the portlet settings as needed.

**Comment by paregorios** [comment]
works. thanks.
