### ISSUE TITLE
full calendar?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#9]
Doesn't seem to be enabled on dev (or on production, despite comments to the contrary in scrumdo). The option to view events as either a listing or a full calendar was meant to be anonymous user-selectable, not something configured once for all by creator/manager.

**Comment by kevintbrooks** [comment]
Here's a look at the full calendar view: ![isaw-09-calview](https://cloud.githubusercontent.com/assets/1392386/7942499/a2a0d0e8-092c-11e5-83d4-4d12fd6a9041.jpg)

**Comment by kevintbrooks** [comment]
And the events lander view (see mini calendar and link to full calendar view) 
![isaw-09-eventlander](https://cloud.githubusercontent.com/assets/1392386/7942530/c64176d8-092c-11e5-8cfb-507c0385aee1.jpg)

**Comment by cguardia** [comment]
@kevintbrooks happily, the calendar header problem is not an issue on staging. There remains the matter of the links to the calendar views, which are at the top of each page right now.

**Comment by cguardia** [comment]
I believe this only needs styling.

**Comment by kevintbrooks** [comment]
Thanks @cguardia . It looks like the minicalendar has disappeared from the event listings page?

Any chance we could get some actual event data in here, as well?

**Comment by cguardia** [comment]
@paregorios maybe you can add a few test events?

@kevintbrooks the calendar portlet presents a bit of a challenge, since it only goes on the folder, not on the events. I can probably set up a theme rule to remove it from event pages. I have added it for the time being, so disregard when you see it on the individual event pages. It will be gone later.
